// Complete metadata and base stats for all 34 Vanilla Characters (17 Standard + 17 Tainted)
export const VANILLA_CHARACTERS = [
  // --- BASE / REGULAR CHARACTERS ---
  {
    id: 0,
    name: 'Isaac',
    skin: 'character_001_isaac.png',
    skinColor: -1,
    hp: 6, // 3 Red Heart containers (in half-hearts)
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 1,
    keys: 0,
    items: [105], // The D6
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Gives an extra item choice for future item pedestals (similar to More Options / There\'s Options).',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_isaac.png',
    bigportrait: 'playerportraitbig_01_isaac.png',
    costume: 0,
    description: 'The standard character with balanced stats and The D6 for rerolling items.'
  },
  {
    id: 1,
    name: 'Magdalene',
    skin: 'character_002_magdalene.png',
    skinColor: -1,
    hp: 8, // 4 Red Heart containers
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [45], // Yum Heart
    trinket: 0,
    card: 0,
    pill: 1, // Full Health or Speed Up
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Increases max heart containers limit to 18 and grants a red heart container.',
    speed: 0.85,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_magdalene.png',
    bigportrait: 'playerportraitbig_02_magdalene.png',
    costume: 7,
    description: 'Tanky character starting with 4 heart containers, a speed-down penalty, and Yum Heart.'
  },
  {
    id: 2,
    name: 'Cain',
    skin: 'character_003_cain.png',
    skinColor: -1,
    hp: 4, // 2 Red Heart containers
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 1,
    items: [46], // Lucky Foot
    trinket: 1, // Paper Clip (unlocked)
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'All arcade and gambling machines have significantly improved winning odds.',
    speed: 1.3,
    damage: 4.2,
    damageMult: 1.2,
    tears: 2.73,
    range: 4.5,
    shotspeed: 1.0,
    luck: 1.0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_cain.png',
    bigportrait: 'playerportraitbig_03_cain.png',
    costume: 8,
    description: 'Fast and high starting damage multiplier (1.2x) with high luck and positive pills.'
  },
  {
    id: 3,
    name: 'Judas',
    skin: 'character_004_judas.png',
    skinColor: -1,
    hp: 2, // 1 Red Heart container
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 3,
    bombs: 0,
    keys: 0,
    items: [34], // Book of Belial
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Book of Belial becomes a passive +2.0 damage buff with active piercing flames.',
    speed: 1.0,
    damage: 4.72,
    damageMult: 1.35,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_judas.png',
    bigportrait: 'playerportraitbig_04_judas.png',
    costume: 9,
    description: 'Glass cannon with 1.35x damage multiplier and the Book of Belial.'
  },
  {
    id: 4,
    name: '??? (Blue Baby)',
    skin: 'character_006_bluebaby.png',
    skinColor: 2,
    hp: 0,
    armor: 6, // 3 Soul Hearts
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [36], // The Poop
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Soul hearts heal twice as much from friendly flies/poop interactions; all soul hearts act like Devil Deal discounts.',
    speed: 1.0,
    damage: 3.68,
    damageMult: 1.05,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_bluebaby.png',
    bigportrait: 'playerportraitbig_06_bluebaby.png',
    costume: 0,
    description: 'Cannot have red heart containers. All health upgrades convert to soul hearts.'
  },
  {
    id: 5,
    name: 'Eve',
    skin: 'character_005_eve.png',
    skinColor: -1,
    hp: 4, // 2 Red Heart containers
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [117, 122], // Dead Bird, Whore of Babylon
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 294, // Razor Blade (unlocked)
    pocketactive: 0,
    birthright: 'Whore of Babylon and Dead Bird remain permanently active regardless of health.',
    speed: 1.23,
    damage: 2.62,
    damageMult: 0.75,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_eve.png',
    bigportrait: 'playerportraitbig_05_eve.png',
    costume: 10,
    description: 'Starts with low damage multiplier (0.75x) but triggers Whore of Babylon at 1 red heart.'
  },
  {
    id: 6,
    name: 'Samson',
    skin: 'character_007_samson.png',
    skinColor: -1,
    hp: 6, // 3 Red Heart containers
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [157], // Bloody Lust
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Bloody Lust damage boost caps at a higher maximum and decays much slower between floors.',
    speed: 1.1,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 5.0,
    shotspeed: 1.31,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_samson.png',
    bigportrait: 'playerportraitbig_07_samson.png',
    costume: 13,
    description: 'Increases damage each time he takes damage on the current floor via Bloody Lust.'
  },
  {
    id: 7,
    name: 'Azazel',
    skin: 'character_008_azazel.png',
    skinColor: 1,
    hp: 0,
    armor: 0,
    black: 6, // 3 Black Hearts
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [], // Innate Short Brimstone + Flying
    trinket: 0,
    card: 1, // The Fool
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Turns short-range mini-Brimstone beam into a wide, full-range piercing laser.',
    speed: 1.25,
    damage: 5.25,
    damageMult: 1.5,
    tears: 2.73,
    range: 4.5,
    shotspeed: 1.0,
    luck: 0,
    flying: true,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_azazel.png',
    bigportrait: 'playerportraitbig_08_azazel.png',
    costume: 11,
    description: 'Demon with innate flight, 1.5x damage multiplier, and a devastating short-range Brimstone beam.'
  },
  {
    id: 8,
    name: 'Lazarus',
    skin: 'character_009_lazarus.png',
    skinColor: -1,
    hp: 6, // 3 Red Heart containers
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [], // Extra life (Lazarus II) + Anemic
    trinket: 0,
    card: 0,
    pill: 1, // Random pill
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Revives into Lazarus II with +1 permanent damage and preserves red heart containers.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: -1.0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_lazarus.png',
    bigportrait: 'playerportraitbig_09_lazarus.png',
    costume: 32,
    description: 'Starts with 1 extra life that revives him as Lazarus II with higher damage and Anemic.'
  },
  {
    id: 9,
    name: 'Eden',
    skin: 'character_009_eden.png',
    skinColor: -1,
    hp: 4,
    armor: 2,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 1,
    keys: 0,
    items: [], // Fully randomized starting passive & active
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Spawns 3 random passive items on pedestals to choose from.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_eden.png',
    bigportrait: 'playerportraitbig_09_eden.png',
    costume: 12,
    description: 'Completely randomized starting health, items, haircuts, and stats on every run.'
  },
  {
    id: 10,
    name: 'The Lost',
    skin: 'character_012_thelost.png',
    skinColor: 0,
    hp: 0,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [313, 609], // Holy Mantle, Eternal D6
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Rerolls and removes all defensive/health items from future item pools.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: true,
    canShoot: true,
    dlc: 'rebirth',
    isTainted: false,
    portrait: 'playerportrait_thelost.png',
    bigportrait: 'playerportraitbig_12_thelost.png',
    costume: 0,
    description: 'Ghost with flight and spectral tears. Free devil deals, dies in 1 hit without Holy Mantle.'
  },
  {
    id: 11,
    name: 'Lilith',
    skin: 'character_014_lilith.png',
    skinColor: 1,
    hp: 2, // 1 Red Heart container
    armor: 4, // 2 Black Hearts
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [357, 360, 412], // Box of Friends, Incubus, Cambion Conception
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'All familiars now duplicate in front of Lilith in a line rather than tailing behind.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: false, // Blindfolded, shoots through Incubus
    dlc: 'afterbirth',
    isTainted: false,
    portrait: 'playerportrait_lilith.png',
    bigportrait: 'playerportraitbig_14_lilith.png',
    costume: 34,
    description: 'Blindfolded mother of demons who shoots exclusively through her familiars.'
  },
  {
    id: 12,
    name: 'Keeper',
    skin: 'character_015_keeper.png',
    skinColor: 5,
    hp: 6, // 3 Coin Hearts (in half-hearts, 6 = 3 coin slots)
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 1,
    bombs: 1,
    keys: 0,
    items: [349], // Wooden Nickel
    trinket: 67, // Store Key
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Increases max coin hearts limit to 4.',
    speed: 0.85,
    damage: 3.5,
    damageMult: 1.2,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: -2.0,
    flying: false,
    canShoot: true,
    dlc: 'afterbirth',
    isTainted: false,
    portrait: 'playerportrait_keeper.png',
    bigportrait: 'playerportraitbig_15_keeper.png',
    costume: 47,
    description: 'Fired triple tears. Heals solely with coin pickups instead of normal hearts.'
  },
  {
    id: 13,
    name: 'Apollyon',
    skin: 'character_016_apollyon.png',
    skinColor: 5,
    hp: 4, // 2 Red Heart containers
    armor: 0,
    black: 2, // 1 Black Heart
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [477], // Void
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Void absorbs items and gains double the stat boosts or spawns extra Locusts.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'afterbirthplus',
    isTainted: false,
    portrait: 'playerportrait_apollyon.png',
    bigportrait: 'playerportraitbig_16_apollyon.png',
    costume: 36,
    description: 'The Destroyer with Void to absorb active and passive items for stat bonuses.'
  },
  {
    id: 14,
    name: 'The Forgotten',
    skin: 'character_017_theforgotten.png',
    skinColor: 5,
    hp: 0,
    armor: 0,
    black: 0,
    bone: 4, // 2 Bone Hearts
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [], // Bone club melee attack
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'The Soul is freed from its chain and can move anywhere in the room while The Forgotten guards.',
    speed: 1.0,
    damage: 5.25,
    damageMult: 1.5,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'afterbirthplus',
    isTainted: false,
    portrait: 'playerportrait_theforgotten.png',
    bigportrait: 'playerportraitbig_17_theforgotten.png',
    costume: 44,
    description: 'Skeleton with bone club melee attack and an ethereal chained Soul.'
  },
  {
    id: 15,
    name: 'Bethany',
    skin: 'character_001x_bethany.png',
    skinColor: -1,
    hp: 6, // 3 Red Heart containers
    armor: 8, // 4 Soul Heart charges
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [584], // Book of Virtues
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Item wisps gain +100% health and fire piercing spectral tears.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: false,
    portrait: 'playerportrait_bethany.png',
    bigportrait: 'playerportraitbig_18_bethany.png',
    costume: 51,
    description: 'Cannot gain soul hearts as HP; soul hearts convert to active item charges and wisps via Book of Virtues.'
  },
  {
    id: 16,
    name: 'Jacob & Esau',
    skin: 'character_002x_jacob.png',
    skinColor: -1,
    hp: 6, // Jacob: 3 Red Hearts, Esau: 1 Red + 1 Soul
    armor: 2,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 1,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Copies 3 random passive items from Jacob to Esau and vice-versa.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: false,
    isDual: true,
    twinSkin: 'character_003x_esau.png',
    twinBaseSkin: 'character_003x_esau.png',
    twinPortrait: 'playerportrait_jacob.png',
    twinBasePortrait: 'playerportrait_jacob.png',
    twinCostume: 53,
    twinSkinColor: 3,
    twinHp: 2,
    twinArmor: 2,
    portrait: 'playerportrait_jacob.png',
    bigportrait: 'playerportraitbig_19_jacob.png',
    costume: 52,
    description: 'Control two characters simultaneously with separate health bars and inventory.'
  },

  // --- TAINTED CHARACTERS (REPENTANCE / REPENTANCE+) ---
  {
    id: 17,
    name: 'Tainted Isaac',
    skin: 'character_001b_isaac.png',
    skinColor: -1,
    hp: 6,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 1,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Increases maximum passive inventory slots from 8 to 12.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_isaac_b.png',
    bigportrait: 'playerportraitbig_01_isaac_b.png',
    costume: 79,
    description: 'Item cycle between 2 choices, but capped at 8 passive items. Items can be dropped.'
  },
  {
    id: 18,
    name: 'Tainted Magdalene',
    skin: 'character_002b_magdalene.png',
    skinColor: -1,
    hp: 8,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [45],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 711, // Yum Heart pocket
    pocketactive: 711,
    birthright: 'Increases temporary heart containers to 18 and grants a permanent red heart container.',
    speed: 1.0,
    damage: 2.62,
    damageMult: 0.75,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_magdalene_b.png',
    bigportrait: 'playerportraitbig_02_magdalene_b.png',
    costume: 80,
    description: 'Heart containers bleed out over time. Can hug enemies to deal massive melee damage and drop half-hearts.'
  },
  {
    id: 19,
    name: 'Tainted Cain',
    skin: 'character_003b_cain.png',
    skinColor: -1,
    hp: 4,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 1,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 706, // Bag of Crafting
    pocketactive: 706,
    birthright: 'All crafted items yield an extra duplicate item or drop extra high-tier pickups.',
    speed: 1.0,
    damage: 4.2,
    damageMult: 1.2,
    tears: 2.73,
    range: 4.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_cain_b.png',
    bigportrait: 'playerportraitbig_03_cain_b.png',
    costume: 81,
    description: 'Item pedestals shatter into pickups. Uses Bag of Crafting to forge any item from 8 ingredients.'
  },
  {
    id: 20,
    name: 'Tainted Judas',
    skin: 'character_004b_judas.png',
    skinColor: 1,
    hp: 0,
    armor: 0,
    black: 4, // 2 Black hearts
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 705, // Dark Arts
    pocketactive: 705,
    birthright: 'Dark Arts grants +50% invulnerability duration and double damage scaling per enemy sliced.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_judas_b.png',
    bigportrait: 'playerportraitbig_04_judas_b.png',
    costume: 82,
    description: 'Shadow entity who turns invulnerable and slices through bullets/enemies with Dark Arts.'
  },
  {
    id: 21,
    name: 'Tainted ???',
    skin: 'character_005b_bluebaby.png',
    skinColor: 2,
    hp: 0,
    armor: 6, // 3 Soul hearts
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 707, // Poop queue pocket
    pocketactive: 707,
    birthright: 'Increases poop capacity to 29 and adds special explosive / gas combos.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_bluebaby_b.png',
    bigportrait: 'playerportraitbig_06_bluebaby_b.png',
    costume: 83,
    description: 'Carries a queue of elemental poops (gas, fire, toxic, stone, holy) to throw like grenades.'
  },
  {
    id: 22,
    name: 'Tainted Eve',
    skin: 'character_006b_eve.png',
    skinColor: -1,
    hp: 4, // 2 Red Heart containers
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 710, // Sumptorium
    pocketactive: 710,
    birthright: 'Blood clots gain 3x max health and never decay on room changes.',
    speed: 1.0,
    damage: 2.97,
    damageMult: 0.85,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_eve_b.png',
    bigportrait: 'playerportraitbig_05_eve_b.png',
    costume: 84,
    description: 'Shoots blood tears that sacrifice health to spawn an army of blood clot familiars.'
  },
  {
    id: 23,
    name: 'Tainted Samson',
    skin: 'character_007b_samson.png',
    skinColor: -1,
    hp: 6,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 704, // Berserk!
    pocketactive: 704,
    birthright: 'Berserk mode duration increased and kills grant +2 seconds of rage.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_samson_b.png',
    bigportrait: 'playerportraitbig_07_samson_b.png',
    costume: 85,
    description: 'Builds rage when striking or taking hits, entering Berserk mode with a jawbone melee weapon.'
  },
  {
    id: 24,
    name: 'Tainted Azazel',
    skin: 'character_008b_azazel.png',
    skinColor: 1,
    hp: 0,
    armor: 0,
    black: 3, // 1.5 Black hearts
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 714, // Hemoptysis
    pocketactive: 714,
    birthright: 'Full-screen sneezing blast that curses all enemies in the room with brimstone vulnerability.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.5,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: true,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_azazel_b.png',
    bigportrait: 'playerportraitbig_08_azazel_b.png',
    costume: 86,
    description: 'Thin full-range Brimstone beam; sneezes blood clouds via Hemoptysis to mark enemies for double damage.'
  },
  {
    id: 25,
    name: 'Tainted Lazarus',
    skin: 'character_009b_lazarus.png',
    skinColor: -1,
    hp: 6,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 713, // Flip
    pocketactive: 713,
    birthright: 'The inactive form fights alongside the active form as a spectral ghost.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_lazarus_b.png',
    bigportrait: 'playerportraitbig_09_lazarus_b.png',
    costume: 87,
    description: 'Alternates between Living Lazarus and Dead Lazarus every room or via Flip, each with distinct builds.'
  },
  {
    id: 26,
    name: 'Tainted Eden',
    skin: 'character_009_eden.png',
    skinColor: -1,
    hp: 4,
    armor: 2,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 1,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Locks all current passive items and stats from being rerolled upon taking damage.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_eden_b.png',
    bigportrait: 'playerportraitbig_09_eden_b.png',
    costume: 88,
    description: 'Taking any damage rerolls all inventory items, stats, and pickups into random ones from the same pools.'
  },
  {
    id: 27,
    name: 'Tainted Lost',
    skin: 'character_012b_thelost.png',
    skinColor: 5,
    hp: 0,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [669], // Sacred Orb passive mechanic (better items)
    trinket: 0,
    card: 32, // Holy Card
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Grants an extra life for Tainted Lost and drops an extra Holy Card.',
    speed: 1.0,
    damage: 4.55,
    damageMult: 1.3,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: true,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_thelost_b.png',
    bigportrait: 'playerportraitbig_12_thelost_b.png',
    costume: 89,
    description: '1.3x damage multiplier, better item pools, but NO Holy Mantle. Dies in 1 hit without Holy Card shields.'
  },
  {
    id: 28,
    name: 'Tainted Lilith',
    skin: 'character_014b_lilith.png',
    skinColor: 1,
    hp: 2,
    armor: 4, // 2 Black hearts
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 709, // Gello
    pocketactive: 709,
    birthright: 'Gello splits into twin demonic fetuses, doubling tear output and whip range.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_lilith_b.png',
    bigportrait: 'playerportraitbig_14_lilith_b.png',
    costume: 90,
    description: 'Whips out her demonic fetus Gello from her stomach to whip enemies and fire tears from distant angles.'
  },
  {
    id: 29,
    name: 'Tainted Keeper',
    skin: 'character_015b_keeper.png',
    skinColor: 5,
    hp: 4, // 2 Coin Hearts
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [], // Innate quad-shot
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Defeated enemies drop temporary coin cascades that attract towards Keeper.',
    speed: 0.9,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: -2.0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_keeper_b.png',
    bigportrait: 'playerportraitbig_15_keeper_b.png',
    costume: 91,
    description: 'Fires quad-shots. Every killed enemy drops coins that vanish quickly. All shops contain 4 items.'
  },
  {
    id: 30,
    name: 'Tainted Apollyon',
    skin: 'character_016b_apollyon.png',
    skinColor: 5,
    hp: 4,
    armor: 2,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 708, // Abyss
    pocketactive: 708,
    birthright: 'Red Locusts from Abyss deal double damage and trigger specialized synergies.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_apollyon_b.png',
    bigportrait: 'playerportraitbig_16_apollyon_b.png',
    costume: 92,
    description: 'Uses Abyss to swallow items and convert them into an aggressive swarm of red attack Locusts.'
  },
  {
    id: 31,
    name: 'Tainted Forgotten',
    skin: 'character_016b_theforgotten.png',
    skinColor: 5,
    hp: 0,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 0,
    pocketactive: 0,
    birthright: 'Grants the Soul a recall ability that immediately pulls the skeleton back to its location with a shockwave.',
    speed: 1.0,
    damage: 5.25,
    damageMult: 1.5,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: true,
    canShoot: false,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_theforgotten_b.png',
    bigportrait: 'playerportraitbig_17_theforgotten_b.png',
    costume: 93,
    description: 'You control an intangible Soul who picks up and throws the immobile Skeleton heap at enemies.'
  },
  {
    id: 32,
    name: 'Tainted Bethany',
    skin: 'character_018b_bethany.png',
    skinColor: -1,
    hp: 6, // 3 Red Heart containers
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 712, // Lemegeton
    pocketactive: 712,
    birthright: 'Lemegeton item wisps gain double health and higher chances to summon Tier 4 items.',
    speed: 1.0,
    damage: 2.62,
    damageMult: 0.75,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_bethany_b.png',
    bigportrait: 'playerportraitbig_18_bethany_b.png',
    costume: 94,
    description: 'Collects blood charges from red hearts to invoke Lemegeton, summoning ghost item wisps that grant passive effects.'
  },
  {
    id: 33,
    name: 'Tainted Jacob',
    skin: 'character_019b_jacob.png',
    skinColor: -1,
    hp: 6,
    armor: 0,
    black: 0,
    bone: 0,
    broken: 0,
    coins: 0,
    bombs: 0,
    keys: 0,
    items: [],
    trinket: 0,
    card: 0,
    pill: 0,
    pocketitem: 722, // Anima Sola
    pocketactive: 722,
    birthright: 'Anima Sola chains dark Esau for twice as long and deals explosive damage when released.',
    speed: 1.0,
    damage: 3.5,
    damageMult: 1.0,
    tears: 2.73,
    range: 6.5,
    shotspeed: 1.0,
    luck: 0,
    flying: false,
    canShoot: true,
    dlc: 'repentance',
    isTainted: true,
    portrait: 'playerportrait_jacob_b.png',
    bigportrait: 'playerportraitbig_19_jacob_b.png',
    costume: 95,
    description: 'Hunted by the demonic flaming ghost of Dark Esau. Chain Esau with Anima Sola to launch him into foes.'
  }
];

export const VANILLA_CHARACTER_SPRITES = new Set([
  // Isaac
  'character_001_isaac.png',
  'character_001_isaac_b.png',
  'character_001b_isaac.png',
  'character_001b_isaacsscars.png',
  // Magdalene
  'character_002_magdalene.png',
  'character_002_magdalene_b.png',
  'character_002b_magdalene.png',
  'character_002_maggiesbeautifulgoldenlocks.png',
  'character_002b_maggiesnotsobeautifulgoldenlocks.png',
  // Cain
  'character_003_cain.png',
  'character_003_cain_b.png',
  'character_003b_cain.png',
  'character_003_cainseyepatch.png',
  // Judas
  'character_004_judas.png',
  'character_004_judas_b.png',
  'character_004b_judas.png',
  'character_004_judasfez.png',
  'character_004b_judasfez.png',
  'character_013_blackjudas.png',
  // Eve
  'character_005_eve.png',
  'character_005_eve_b.png',
  'character_006b_eve.png',
  'character_005_evehead.png',
  'character_006b_evehead.png',
  // Blue Baby
  'character_005b_bluebaby.png',
  'character_006_bluebaby.png',
  'character_006_bluebaby_b.png',
  'character_005b_bluebabybody.png',
  'character_005b_bluebabyhead.png',
  // Samson
  'character_007_samson.png',
  'character_007_samson_b.png',
  'character_007b_samson.png',
  'character_007_samsonshairandbandanna.png',
  'character_007b_samsonshair.png',
  // Azazel
  'character_008_azazel.png',
  'character_008_azazel_b.png',
  'character_008b_azazel.png',
  'character_008_azazelhead.png',
  'character_008_azazelhead_2.png',
  'character_008_azazelhead_hair.png',
  'character_008b_azazelbody.png',
  'character_008b_azazelhead.png',
  // Lazarus
  'character_009_lazarus.png',
  'character_009_lazarus2.png',
  'character_009_lazarus_b.png',
  'character_009_lazarus2_b.png',
  'character_009b_lazarus.png',
  'character_009b_lazarus2.png',
  'character_009_lazarushair.png',
  'character_009_lazarushair2.png',
  'character_009b_lazarus2hair.png',
  'character_009b_lazarusbody.png',
  'character_009b_lazarushair.png',
  'character_010_lazarus2.png',
  // Eden
  'character_009_eden.png',
  'character_009_eden_b.png',
  'character_010_eden.png',
  'character_010_eden_b.png',
  // The Lost
  'character_011_thelost.png',
  'character_011_thelost_b.png',
  'character_012_thelost.png',
  'character_012_thelost_b.png',
  'character_012b_thelost.png',
  'character_012_thelost1.png',
  'character_012_thelost_hair.png',
  'character_012b_lostcobwebs.png',
  // Lilith
  'character_013_lilith.png',
  'character_013_lilith_b.png',
  'character_014_lilith.png',
  'character_014_lilith_b.png',
  'character_014b_lilith.png',
  'character_014_lilithhair.png',
  'character_014b_lilithbody.png',
  'character_014b_lilithhair.png',
  // Keeper
  'character_014_keeper.png',
  'character_014_keeper_b.png',
  'character_015_keeper.png',
  'character_015_keeper_b.png',
  'character_015b_keeper.png',
  'character_015_keepernoose.png',
  'character_015b_keeperisgreedier.png',
  'character_015b_keeperissadder.png',
  // Apollyon
  'character_015_apollyon.png',
  'character_015_apollyon_b.png',
  'character_016_apollyon.png',
  'character_016_apollyon_b.png',
  'character_016b_apollyon.png',
  'character_016_apollyonhorns.png',
  'character_016b_apollyonhorns.png',
  'character_016b_apollyonvoid.png',
  // The Forgotten & The Soul
  'character_016_theforgotten.png',
  'character_016_theforgotten_b.png',
  'character_016_thesoul.png',
  'character_016_thesoul_b.png',
  'character_016b_theforgotten.png',
  'character_016b_thesoul.png',
  'character_016b_theforgottenbody.png',
  'character_016b_theforgottencracks.png',
  'character_017_theforgotten.png',
  'character_017_theforgotten_b.png',
  'character_017_thesoul.png',
  'character_017_thesoul_b.png',
  'character_017_theforgottenbody.png',
  'character_017b_thesoul.png',
  'character_017b_thesoulshood.png',
  'character_018_thesoul.png',
  // Bethany
  'character_001x_bethany.png',
  'character_017_bethany.png',
  'character_017_bethany_b.png',
  'character_018_bethany.png',
  'character_018_bethany_b.png',
  'character_018b_bethany.png',
  'character_001x_bethshair.png',
  'character_018b_bethshair.png',
  // Jacob & Esau
  'character_002x_jacob.png',
  'character_003x_esau.png',
  'character_018_jacob.png',
  'character_018_jacob_b.png',
  'character_018_esau.png',
  'character_018_esau_b.png',
  'character_019_jacob.png',
  'character_019_jacob_b.png',
  'character_019_esau.png',
  'character_019_esau_b.png',
  'character_019b_jacob.png',
  'character_019b_jacob2.png',
  'character_019b_esau.png',
  'character_002x_jacobhair.png',
  'character_003x_esauhair.png',
  'character_019b_jacobhair.png',
  'character_019b_jacob2hair.png',
  // Base utility sheets
  'character_custom.png',
  'character_ghost.png',
  'character_skeleton.png'
]);

export const VANILLA_PORTRAITS = new Set([
  'playerportrait_isaac.png', 'playerportrait_isaac_b.png', 'playerportrait_01_isaac.png', 'playerportrait_01_isaac_b.png',
  'playerportrait_magdalene.png', 'playerportrait_magdalene_b.png', 'playerportrait_02_magdalene.png', 'playerportrait_02_magdalene_b.png',
  'playerportrait_cain.png', 'playerportrait_cain_b.png', 'playerportrait_03_cain.png', 'playerportrait_03_cain_b.png',
  'playerportrait_judas.png', 'playerportrait_judas_b.png', 'playerportrait_04_judas.png', 'playerportrait_04_judas_b.png', 'playerportrait_blackjudas.png',
  'playerportrait_eve.png', 'playerportrait_eve_b.png', 'playerportrait_05_eve.png', 'playerportrait_05_eve_b.png',
  'playerportrait_bluebaby.png', 'playerportrait_bluebaby_b.png', 'playerportrait_06_bluebaby.png', 'playerportrait_06_bluebaby_b.png',
  'playerportrait_samson.png', 'playerportrait_samson_b.png', 'playerportrait_07_samson.png', 'playerportrait_07_samson_b.png',
  'playerportrait_azazel.png', 'playerportrait_azazel_b.png', 'playerportrait_08_azazel.png', 'playerportrait_08_azazel_b.png',
  'playerportrait_lazarus.png', 'playerportrait_lazarus_b.png', 'playerportrait_09_lazarus.png', 'playerportrait_09_lazarus_b.png', 'playerportrait_lazarus2.png', 'playerportrait_lazarus2_b.png',
  'playerportrait_eden.png', 'playerportrait_eden_b.png', 'playerportrait_09_eden.png', 'playerportrait_09_eden_b.png', 'playerportrait_10_eden.png', 'playerportrait_10_eden_b.png',
  'playerportrait_thelost.png', 'playerportrait_thelost_b.png', 'playerportrait_11_thelost.png', 'playerportrait_11_thelost_b.png', 'playerportrait_12_thelost.png', 'playerportrait_12_thelost_b.png',
  'playerportrait_lilith.png', 'playerportrait_lilith_b.png', 'playerportrait_13_lilith.png', 'playerportrait_13_lilith_b.png', 'playerportrait_14_lilith.png', 'playerportrait_14_lilith_b.png',
  'playerportrait_keeper.png', 'playerportrait_keeper_b.png', 'playerportrait_14_keeper.png', 'playerportrait_14_keeper_b.png', 'playerportrait_15_keeper.png', 'playerportrait_15_keeper_b.png',
  'playerportrait_apollyon.png', 'playerportrait_apollyon_b.png', 'playerportrait_15_apollyon.png', 'playerportrait_15_apollyon_b.png', 'playerportrait_16_apollyon.png', 'playerportrait_16_apollyon_b.png',
  'playerportrait_theforgotten.png', 'playerportrait_theforgotten_b.png', 'playerportrait_16_theforgotten.png', 'playerportrait_16_theforgotten_b.png', 'playerportrait_17_theforgotten.png', 'playerportrait_17_theforgotten_b.png', 'playerportrait_thesoul.png', 'playerportrait_thesoul_b.png',
  'playerportrait_bethany.png', 'playerportrait_bethany_b.png', 'playerportrait_17_bethany.png', 'playerportrait_17_bethany_b.png', 'playerportrait_18_bethany.png', 'playerportrait_18_bethany_b.png',
  'playerportrait_jacob.png', 'playerportrait_jacob_b.png', 'playerportrait_18_jacob.png', 'playerportrait_18_jacob_b.png', 'playerportrait_19_jacob.png', 'playerportrait_19_jacob_b.png', 'playerportrait_esau.png', 'playerportrait_esau_b.png', 'playerportrait_jacob_b_darkesau.png'
]);

export const VANILLA_NAME_KEYS = [
  'isaac', 'magdalene', 'maggie', 'cain', 'judas', 'bluebaby', 'eve', 'samson', 'azazel', 'lazarus',
  'eden', 'thelost', 'lost', 'lilith', 'keeper', 'apollyon', 'theforgotten', 'forgotten', 'thesoul', 'soul',
  'bethany', 'jacob', 'esau', 'darkjudas', 'blackjudas', 'darkesau'
];

export function isVanillaCharacterFile(fileName) {
  if (!fileName || typeof fileName !== 'string') return false;
  const lower = fileName.toLowerCase();
  const base = lower.replace(/_(?:black|blue|green|grey|gray|red|white)\.png$/, '.png');
  if (VANILLA_CHARACTER_SPRITES.has(base) || VANILLA_CHARACTER_SPRITES.has(lower)) return true;
  if (/^character_009_edenhair\d+\.png$/.test(lower)) return true;
  if (/^character_\d{3}[a-z0-9_]*\.png$/.test(lower)) {
    // Verify it's in the vanilla character numbering range (001 to 020)
    const numMatch = lower.match(/^character_(\d{3})/);
    if (numMatch) {
      const num = parseInt(numMatch[1], 10);
      if (num >= 1 && num <= 20) return true;
    }
  }
  return false;
}

export function isVanillaPortraitFile(fileName) {
  if (!fileName || typeof fileName !== 'string') return false;
  const lower = fileName.toLowerCase();
  if (VANILLA_PORTRAITS.has(lower)) return true;
  if (/^playerportrait_(?:big_)?\d{2}_[a-z0-9_]+\.png$/.test(lower)) return true;
  if (/^playerportrait_(?:big_)?[a-z0-9_]+\.png$/.test(lower)) {
    for (const k of VANILLA_NAME_KEYS) {
      if (lower.includes(k)) return true;
    }
  }
  if (/^playername_(?:\d{2}_)?[a-z0-9_]+\.png$/.test(lower)) {
    for (const k of VANILLA_NAME_KEYS) {
      if (lower.includes(k)) return true;
    }
  }
  if (/^charselect_(?:\d{2}_)?[a-z0-9_]+\.png$/.test(lower)) return true;
  return false;
}


